<?php

namespace Hotel\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FloorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FloorRepository extends EntityRepository
{
}
