<?php

namespace Hotel\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    public function getNewsWithAuthor()
    {
        $qb = $this->createQueryBuilder('newsRepository')
            ->select('newsRepository', 'author')
            ->leftJoin('newsRepository.author', 'author')
            ->orderBy('newsRepository.modifiedDate', 'DESC')
        ;

        return $qb->getQuery()->getResult();
    }

    public function getSliderWithNews()
    {
        $qb = $this->createQueryBuilder('newsRepository')
            ->select('newsRepository')
            ->leftJoin('newsRepository.slider', 'slider')
            ->orderBy('newsRepository.createDate', 'DESC')
            ->setMaxResults(5)
        ;
        return $qb->getQuery()->getResult();
    }
}
