<?php

namespace Hotel\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SliderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SliderRepository extends EntityRepository
{
    public function getSliderWithNews()
    {
        $qb = $this->createQueryBuilder('sliderRepository')
            ->select('sliderRepository', 'news')
            ->leftJoin('sliderRepository.news', 'news')
        ;

        return $qb->getQuery()->getArrayResult();
    }
}
