fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

hotel_file_manager:
    resource: "@HotelFileManagerBundle/Resources/config/routing.yml"
    prefix:   /

hotel_admin:
    resource: "@HotelAdminBundle/Resources/config/routing.yml"
    prefix:   /

hotel_front:
    resource: "@HotelFrontBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
